PROGRAM P6
    IMPLICIT NONE
    CHARACTER(LEN=10) :: DATE
    CHARACTER(LEN=2) :: MONTH
    WRITE(UNIT=*, FMT=*) "NAPISZ DATE W FORMACIE YYYY-MM-DD"
    READ(UNIT=*, FMT=*) DATE
    MONTH=DATE(6:7)
    WRITE(UNIT=*, FMT="(A10)") MONTH
    
    SELECT CASE(MONTH)
    CASE("03":"05")
        WRITE(UNIT=*, FMT="(A12)") "TO WIOSNA"
    CASE("06", "07", "08")
        WRITE(UNIT=*, FMT="(A12)") "TO LATO"
    CASE DEFAULT
        WRITE(UNIT=*, FMT="(A25)") "TO ANI WIOSNA ANI LATO"
    END SELECT
    
    STOP
END PROGRAM P6